version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data  # Menyimpan data di volume Elasticsearch
    networks:
      - defaults

  logstash:
    image: docker.elastic.co/logstash/logstash:8.5.0
    environment:
      - LOGSTASH_HOST=logstash
    volumes:
      - ./elk/logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
    networks:
      - defaults

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.0
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - defaults
  
  postgres:
    image: postgres
    container_name: postgres
    platform: linux/amd64
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: financial-tracking
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - defaults

  redis:
    image: redis
    container_name: redis
    platform: linux/amd64
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - defaults

  mysql:
    image: mysql:5.7
    container_name: mysql
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - defaults
  
networks:
  defaults:
    driver: bridge

volumes:
  esdata:
    # driver: local  # Gunakan driver volume lokal untuk data Elasticsearch
  postgres_data:
    # driver: local
