version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data  # Menyimpan data di volume Elasticsearch
    networks:
      - defaults

  logstash:
    image: docker.elastic.co/logstash/logstash:8.5.0
    environment:
      - LOGSTASH_HOST=logstash
    volumes:
      - ./elk/logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
    networks:
      - defaults

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.0
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - defaults

networks:
  defaults:
    driver: bridge

volumes:
  esdata:
    driver: local  # Gunakan driver volume lokal untuk data Elasticsearch
