CREATE TABLE IF NOT EXISTS balances (
    id SERIAL PRIMARY KEY NOT NULL,
    user_id SERIAL UNIQUE NOT NULL,
    finance_account_id SERIAL UNIQUE NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL
);

